// <auto-generated />
using GeekShopping.Api.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.Api.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20240215001850_AddSeedDataProduct")]
    partial class AddSeedDataProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.Api.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("img_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 3L,
                            CategoryName = "Brinquedo",
                            Description = "Capacete do Dather Vader",
                            ImgUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/3_vader.jpg",
                            Name = "Capacete Darth Vader",
                            Price = 350.99m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Brinquedo",
                            Description = "Boneco Storm Tropper",
                            ImgUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/4_storm_tropper.jpg",
                            Name = "Boneco Storm Tropper",
                            Price = 150m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Camiseta",
                            Description = "Camiseta 100% Gamer",
                            ImgUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/5_100_gamer.jpg",
                            Name = "Camiseta 100% Gamer",
                            Price = 45.99m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Camiseta",
                            Description = "Camiseta SpaceX",
                            ImgUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/6_spacex.jpg",
                            Name = "Camiseta SpaceX",
                            Price = 40m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Camiseta",
                            Description = "Camiseta Coffee",
                            ImgUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/7_coffee.jpg",
                            Name = "Camiseta Coffee",
                            Price = 35.99m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Blusa",
                            Description = "Blusa Cobra Kai",
                            ImgUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/8_moletom_cobra_kay.jpg",
                            Name = "Blusa Cobra Kai",
                            Price = 150m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Livro",
                            Description = "Livro Star Talk",
                            ImgUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/9_neil.jpg",
                            Name = "Livro Star Talk",
                            Price = 30m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Brinquedo",
                            Description = "Milennium Falcon",
                            ImgUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/10_milennium_falcon.jpg",
                            Name = "Milennium Falcon",
                            Price = 250.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
